// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XtramileWeather.Infrastructure.Persistence;

#nullable disable

namespace XtramileWeather.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20260919065937_InitialCountryCitySchema")]
    partial class InitialCountryCitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("XtramileWeather.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Name")
                        .IsUnique();

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "AU",
                            Latitude = -33.8688m,
                            Longitude = 151.2093m,
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "AU",
                            Latitude = -37.8136m,
                            Longitude = 144.9631m,
                            Name = "Melbourne"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "AU",
                            Latitude = -27.4698m,
                            Longitude = 153.0251m,
                            Name = "Brisbane"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "ID",
                            Latitude = -6.2088m,
                            Longitude = 106.8456m,
                            Name = "Jakarta"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "ID",
                            Latitude = -7.2575m,
                            Longitude = 112.7521m,
                            Name = "Surabaya"
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "ID",
                            Latitude = -6.9175m,
                            Longitude = 107.6191m,
                            Name = "Bandung"
                        },
                        new
                        {
                            Id = 7,
                            CountryCode = "MY",
                            Latitude = 3.1390m,
                            Longitude = 101.6869m,
                            Name = "Kuala Lumpur"
                        },
                        new
                        {
                            Id = 8,
                            CountryCode = "MY",
                            Latitude = 5.4141m,
                            Longitude = 100.3288m,
                            Name = "George Town"
                        },
                        new
                        {
                            Id = 9,
                            CountryCode = "MY",
                            Latitude = 1.4927m,
                            Longitude = 103.7414m,
                            Name = "Johor Bahru"
                        },
                        new
                        {
                            Id = 10,
                            CountryCode = "SG",
                            Latitude = 1.3521m,
                            Longitude = 103.8198m,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 11,
                            CountryCode = "US",
                            Latitude = 40.7128m,
                            Longitude = -74.0060m,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 12,
                            CountryCode = "US",
                            Latitude = 34.0522m,
                            Longitude = -118.2437m,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 13,
                            CountryCode = "US",
                            Latitude = 41.8781m,
                            Longitude = -87.6298m,
                            Name = "Chicago"
                        });
                });

            modelBuilder.Entity("XtramileWeather.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Code = "US",
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("XtramileWeather.Domain.Entities.City", b =>
                {
                    b.HasOne("XtramileWeather.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
